from typing import Callable, Protocol, Union, Dict, Any, Tuple, Awaitable
from typing_extensions import Literal, TypedDict
import pydantic

__all__ = [
    "FunctionCall_Dict",
    "NameArgsTuple",
    "Ollama_ToolCall",
    "OpenAI_ChatCompletionMessageToolCall",
    "Function",
    "AsyncFunction",
    "ToolCall_Union",
    "DecoratedFunction",
    "DecoratedAsyncFunction",
]


class DecoratedFunction(Protocol):
    parameter_decorators: Dict[str, Any]
    libcommand: Any

    def __call__(self, *args: Any, **kwargs: Any) -> Any:
        """
        Allows the DecoratedFunction to be called like a regular function.
        """
        raise NotImplementedError("Subclasses must implement the __call__ method.")


AsyncFunction = Callable[[Any, Any], Awaitable[Any]]


class DecoratedAsyncFunction(Protocol):
    parameter_decorators: Dict[str, Any]
    libcommand: Any

    async def __call__(self, *args: Any, **kwargs: Any) -> Awaitable[Any]:
        """
        Allows the DecoratedAsyncFunction to be called like a regular asynchronous function.
        """
        raise NotImplementedError("Subclasses must implement the __call__ method.")


class FunctionCall_Dict(TypedDict):
    name: str
    arguments: Union[str, Dict[str, Any], None]


NameArgsTuple = Tuple[str, Union[str, Dict[str, Any], None]]


class Function(pydantic.BaseModel):
    arguments: str
    """
    The arguments to call the function with, as generated by the model in JSON
    format. Note that the model does not always generate valid JSON, and may
    hallucinate parameters not defined by your function schema. Validate the
    arguments in your code before calling your function.
    """

    name: str
    """The name of the function to call."""


class OpenAI_ChatCompletionMessageToolCall(pydantic.BaseModel):
    id: str
    """The ID of the tool call."""

    function: Function
    """The function that the model called."""

    type: Literal["function"]
    """The type of the tool. Currently, only `function` is supported."""


class Ollama_ToolCall(pydantic.BaseModel):
    function: Function
    """The function that the model called."""

    type: Literal["function"]
    """The type of the tool. Currently, only `function` is supported."""


ToolCall_Union = Union[Ollama_ToolCall, OpenAI_ChatCompletionMessageToolCall]
